<?xml version="1.0" encoding="utf-8"?>
<testsuite errors="0" failures="1" name="xmlrunner.tests.testsuite_cases.FailedTestCase" tests="1" time="0.000">
	<testcase classname="xmlrunner.tests.testsuite_cases.FailedTestCase" name="test_failure" time="0.000">
		<failure message="" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "{{PATH}}/src/xmlrunner/tests/testsuite_cases.py", line 21, in test_failure
    self.assertTrue(None)
AssertionError
]]>		</failure>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[another text
]]>	</system-err>
</testsuite>
